services:
  playlist_scraper:
    image: "node:24-alpine"
    container_name: "playlist_scraper"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    environment:
      - NODE_ENV=production
    ports:
      - 4242:4242
    command: ["npm", "start"]
